# Generated by Django 5.2 on 2026-06-29 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Uauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('CALCUL', 'Calcul et Opérations'), ('GEOMETRIE', 'Géométrie et Formes'), ('DENOMBREMENT', 'Dénombrement et Nombres'), ('GRANDEURS', 'Grandeurs ET Mésures')], max_length=50)),
                ('points', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('temps', models.IntegerField()),
                ('date_realisation', models.DateField(auto_now_add=True)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_quiz', to='Uauth.enfant')),
            ],
            options={
                'verbose_name': 'Score quiz',
                'ordering': ['-date_realisation'],
            },
        ),
    ]
