# Generated by Django 5.2 on 2026-06-29 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Uauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre de la leçon')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('contenu', models.TextField(blank=True, null=True, verbose_name="Contenu généré par l'IA")),
                ('classe', models.CharField(choices=[('CP1', 'CP1'), ('CP2', 'CP2'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2')], max_length=20, verbose_name='Classe cible')),
                ('duree', models.CharField(blank=True, default='45 min', max_length=50, null=True, verbose_name='Durée estimée')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publiée')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('theme', models.CharField(choices=[('CALCUL', 'Calcul et Opérations'), ('GEOMETRIE', 'Géométrie et Formes'), ('DENOMBREMENT', 'Dénombrement et Nombres'), ('GRANDEURS', 'Grandeurs et Mesures')], max_length=50, verbose_name='Thème mathématique')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='Uauth.enseignant', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('reponse_correcte', models.CharField(max_length=255, verbose_name='Bonne réponse')),
                ('mauvaises_reponses', models.CharField(blank=True, help_text='Séparez les mauvaises réponses par des virgules', max_length=500, null=True, verbose_name='Mauvaises réponses')),
                ('explication', models.TextField(blank=True, null=True, verbose_name='Explication')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='enseignant.lecon', verbose_name='Leçon parente')),
            ],
            options={
                'verbose_name': 'Exercice',
                'verbose_name_plural': 'Exercices',
                'ordering': ['ordre', 'date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EvenementCalendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('type_evenement', models.CharField(choices=[('cours', 'Cours'), ('reunion', 'Réunion'), ('autre', 'Autre')], default='cours', max_length=50, verbose_name="Type d'événement")),
                ('date', models.DateField(verbose_name='Date')),
                ('heure', models.TimeField(verbose_name='Heure')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='Uauth.enseignant', verbose_name='Enseignant')),
                ('lecon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='enseignant.lecon', verbose_name='Leçon liée')),
            ],
            options={
                'verbose_name': 'Événement du calendrier',
                'verbose_name_plural': 'Événements du calendrier',
                'ordering': ['date', 'heure'],
            },
        ),
    ]
