# Generated by Django 5.2 on 2026-07-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0002_add_scheduled_publication_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='donnees_exercice',
            field=models.JSONField(blank=True, help_text='Données structurées additionnelles au format JSON', null=True, verbose_name="Données de l'exercice"),
        ),
        migrations.AddField(
            model_name='exercice',
            name='type_exercice',
            field=models.CharField(choices=[('QCM', 'Question à Choix Multiples'), ('CALCUL_ECRIT', 'Calcul Écrit en Colonnes'), ('CALCUL_MENTAL', 'Calcul Mental Rapide'), ('PROBLEME', 'Résolution de Problème')], default='QCM', max_length=20, verbose_name="Type d'exercice"),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='mauvaises_reponses',
            field=models.CharField(blank=True, help_text='Séparez les mauvaises réponses par des virgules (seulement pour QCM)', max_length=500, null=True, verbose_name='Mauvaises réponses'),
        ),
    ]
