# Generated by Django 5.2 on 2026-06-29 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Uauth', '0001_initial'),
        ('enseignant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Message')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
                ('est_modifie', models.BooleanField(default=False)),
                ('classe_enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_classe', to='Uauth.enseignant')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
                ('groupe_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_groupe_parent', to='Uauth.parent')),
                ('receveur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('LECON_PUBLIEE', 'Nouvelle Leçon'), ('LECTURE_COURS', 'Cours Lu'), ('EXERCICE_FINI', 'Exercice Terminé'), ('QUIZ_FINI', 'Quiz Terminé'), ('MESSAGE_RECU', 'Nouveau Message')], max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
                ('lecon_liee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enseignant.lecon')),
                ('receveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ResultatExercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_eleve', models.CharField(max_length=255)),
                ('est_correct', models.BooleanField()),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_exercices', to='Uauth.enfant')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='enseignant.exercice')),
            ],
            options={
                'verbose_name': "Résultat d'exercice",
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='SuiviLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_lecture', models.DateTimeField(auto_now_add=True)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Uauth.enfant')),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignant.lecon')),
            ],
            options={
                'verbose_name': 'Suivi de lecture',
                'unique_together': {('enfant', 'lecon')},
            },
        ),
    ]
